apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: backend-deployment
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 31019
