apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: backend-deployment
          image: wededo4644/assignment_backend:29
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "400m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "512Mi"
