apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend_deployment
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend_deployment
  template:
    metadata:
      labels:
        app: backend_deployment
    spec:
      containers:
        - name: backend_deployment
          image: wededo4644/assignment_backend:28
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "400m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "512Mi"
