apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: frontend-deployment
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4200
