apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend_deployment
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend_deployment
  template:
    metadata:
      labels:
        app: frontend_deployment
    spec:
      containers:
        - name: frontend_deployment
          image: wededo4644/assignment_frontend:20
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "512Mi"
