apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: frontend-deployment
          image: wededo4644/assignment_frontend:130
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "512Mi"
