apiVersion: v1
kind: Service
metadata:
  name: frontend_service
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: frontend_deployment
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4200
      nodePort: 31004
